#!/usr/bin/env bash
# Install and configure nginx on the server

sudo apt-get update -y
sudo apt-get upgrade -y
apt-get install nginx -y
echo "Hello World!" > /var/www/html/index.html
service nginx start
