#!/usr/bin/env bash
# Installs, configures and starts the server
sudo apt-get update
sudo apt-get -y install nginx
sudo chown -R "$USER":"$USER" /var/www/html
echo 'Hello World!' > /var/www/html/index.html
line="\\\\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}"
sed -i "48i $line" /etc/nginx/sites-enabled/default
sudo service nginx restart

