#!/usr/bin/env bash
# Configure Nginx server so that /redirect_me is redirecting to another page
# But the main domain still shows Hello world

sudo apt-get update -y && apt-get upgrade -y
sudo apt-get install nginx -y
sudo chown -R "$USER":"$USER" /var/www/html
echo "Hello World!" > /var/www/html/index.nginx-debian.html
line="\\\\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}"
sed -i "48i $line" /etc/nginx/sites-available/default

sudo mkdir -p /var/www/default
sudo chown -R "$USER":"$USER"
sudo echo "Ceci n'est pas une page" > /var/www/default/404.html
line1="\\\\tlocation /404.html {\n\t\t root /var/www/default;\n\t}"
sed -i "29i $line1" /etc/nginx/sites-enabled/default
line2="\\\\terror_page 404 /404.html;"
sed -i "32i $line2" /etc/nginx/sites-enabled/default

service nginx restart
