#!/usr/bin/env bash

sudo apt update -y
sudo apt upgrade -y
sudo apt install haproxy -y
sudo chown -R "$USER":"$USER" /etc/haproxy/haproxy.cfg
echo -e "\nfrontend web_frontend\n\tbind *:80\n\tdefault_backend web_backend" >> /etc/haproxy/haproxy.cfg
echo -e "\nbackend web_backend\n\tbalance roundrobin\n\tserver web-01 35.180.202.48:80 check\n\tserver web-02 13.36.243.93:80 check" >> /etc/haproxy/haproxy.cfg

sudo service haproxy restart

